### ISSUE TITLE
Feature selection with Survival-SVM

### ISSUE THREAD

**Issue by darentsai** [imbs-hl/survivalsvm#14]
Dear maintainers,

I'm using this excellent package to conduct my research. This package has implemented the SVM methods for survival analysis from <ins> Van Belle </ins> et al. According to their [Bioinformatics paper (2011)](https://academic.oup.com/bioinformatics/article/27/1/87/202105): "***Improved performance on high-dimensional survival data by application of Survival-SVM***",  a feature selection technique is proposed in ***Section 2.3.2 & 2.3.3***.

Is this package able to deal with this part? Or do you intend to implement this useful technique in the future?

Best regards,
Darren Tsai

**Comment by fouodo** [comment]
Dear Darren,

Variable selection has yet to be implemented in survivalsvm. Implementing it is a good idea, but it cannot be promised to be done soon.

Best wishes,
Cesaire

On 7. May 2024, at 14:48, Darren Tsai ***@***.******@***.***>> wrote:



Dear maintainers,

I'm using this excellent package to conduct my research. This package has implemented the SVM methods for survival analysis from Van Belle et al. According to their Bioinformatics paper (2011)<https://academic.oup.com/bioinformatics/article/27/1/87/202105>, a feature selection technique is proposed in Section 2.3.2 & 2.3.3. Is this package able to deal with this part? Or do you intend to implement this technique in the future?

Best regards,
Darren Tsai

**Comment by darentsai** [comment]
Thanks for the reply. Look forward to see new features in this package!
