### ISSUE TITLE
How to extract the prediction weight of each variable

### ISSUE THREAD

**Issue by chengwenxuan1997** [imbs-hl/survivalsvm#8]
Thanks for the powerful tools, but I was confused about how to measure the importance of each variable. Thus it was difficult to explain which variable plays the main role in the prediction, 

As [Maverick Meerkat](https://stackoverflow.com/users/6296435/maverick-meerkat) says, the weight can be calculated as `t(fit$SV)%*% fit$coefs` when the binary classification.  So could I use a similar definition `t(fit$model.fit$SV) %*% fit$model.fit$Beta` as the weight of each variable? Or any other options? Thanks.

**Comment by fouodo** [comment]
Hi,

thanks for using survivalsvm. The package is not intended to compute variable importance.

Best wishes,
Cesaire

On 12. Oct 2022, at 15:41, Eric ***@***.******@***.***>> wrote:



Thanks for the powerful tools, but I was confused about how to measure the importance of each variable. Thus it was difficult to explain which variable plays the main role in the prediction,

As Maverick Meerkat<https://stackoverflow.com/users/6296435/maverick-meerkat> says, the weight can be calculated as t(fit$SV) %% fit$coefs when the binary classification. So could I use a similar definition t(fit$model.fit$SV) %% fit$model.fit$Beta, as the weight of each variable?

**Comment by chengwenxuan1997** [comment]
OK, thanks. But if I want to apply the trained model to new samples to divide them into high/low-risk groups, could I treat `predict(fit, as.data.frame(new_data))$predicted` as a risk score and divide these samples by median value?
